--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  tasks:
    - name: Creates CentOS7 instance
      ec2:
        key_name:     
        instance_type: t2.micro
        image: 
        count: 1
        vpc_subnet_id: 
        region: us-east-2
        instance_tags:
          Name: CentOS7
        wait: yes
        assign_public_ip: yes


    - name: Creates Debian instance
      ec2:
        key_name:    
        instance_type: t2.micro
        image: 
        count: 1
        vpc_subnet_id: 
        region: us-east-2
        instance_tags:
          Name: DEBIAN_GNU
        wait: yes
        assign_public_ip: yes
        user_data:
                  #!/bin/sh
                  sudo apt-get install python -y
                  sudo pip install boto


    - name: Creates Ubuntu instance
      ec2:
        key_name:   
        instance_type: t2.micro
        image: 
        count: 1
        vpc_subnet_id: 
        region: us-east-2
        instance_tags:
          Name: UBUNTU
        wait: yes
        assign_public_ip: yes
        user_data:
                  #!/bin/sh
                  sudo apt-get install python -y
                  sudo pip install boto