---
- name: Installs r1soft agent 
  hosts: target
  become: yes
  become_method: sudo
  tasks: 
    - block: 
      - name: Create Repository
        copy:
          src: r1soft.repo
          dest: /etc/yum.repos.d/r1soft.repo  

    - name:  Install r1soft agent 
      package: 
        name: serverbackup-enterprise-agent 
        state: latest   
      notify: R1SOFT_INSTALLED   


    - name: Start agent 
      systemd:
        name: sbm-agent
        state: restarted
       
    - name: Get key
      shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"     
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


  handlers: 
    - name: R1SOFT_INSTALLED_ON_CENTOS_7
      systemd:
       name: sbm-agent 
       state: restarted 

        



    #this line is for centos6
    - block: 
       - name: Create Repository
         copy:
           src: r1soft.repo
           dest: /etc/yum.repos.d/r1soft.repo  

    - name:  Install r1soft agent 
      package: 
        name: serverbackup-enterprise-agent 
        state: latest      


    - name: Start agent 
      systemd:
        name: sbm-agent
        state: restarted
       
    - name: Get key
      shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"     
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
        


