--- #we can restart os 
- name: Restart all types of OS
  vars_prompt:
    - name: OS_TYPE
      prompt: "What OS to restart?"
      private: no
  hosts: localhost
  tasks:
    - name: Restarts 
      when: ansible_distribution == "{{OS_TYPE}}"
      reboot:
