---
- hosts: localhost
  tasks: 
    - name: Updates a kernel to latest
      package:
        name: kernel 
        state: latest 
      become: yes
      become_method: sudo 
    - name: restart the system 
      reboot: