--- 
- name: Installs wordpress 
  hosts: localhost
  become: yes
  become_method: sudo 
  gather_facts: no
  ignore_errors: true
  connection: ssh #connection part, how to connect to remote system 
  tasks:
    - name: Install necessary packages 
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - wget
        - unzip
        - php-gd
        - httpd 
        - mysql
        - mariadb-server
        - php 
        - php-mysql
        - php-fpm 
      ignore_errors: true 

    - name: Download wordpress package
      get_url:
        url: "https://wordpress.org/wordpress-5.3.1.tar.gz"
        dest: /tmp/

    - name: unzip wordpress file 
      unarchive:
        src: "/tmp/wordpress-5.3.1.tar.gz"
        dest: /var/www/html/
        remote_src: yes
      become: yes
      become_method: sudo 

    - name: Move files to html folder
      shell: "mv/var/www/html/wordpress/* /var/www/html"  
      become: yes
      become_method: sudo 
      ignore_errors: yes

    - name: Restart httpd
      systemd: 
        name: httpd
        state: restarted
        enabled: yes
      become: yes
      become_method: sudo 

        




      

