--- #sudo pip install boto
- name: Creates ec2 instances
  hosts: localhost
  connection: local
  become: False
  tasks:
    - name: Creates CentOS7 instance
      ec2:
        key_name:   ansible-tower  
        instance_type: t2.micro
        image: 
        count: 3
        vpc_subnet_id: subnet-1c871974 
        region: ca-central-1
        instance_tags:
          Name: CentOS7
        wait: yes
        assign_public_ip: yes




    - name: Creates CentOS6 instance
      ec2:
        key_name:   ansible-tower  
        instance_type: t2.micro
        image: ami-085d04643277add4a
        count: 3
        vpc_subnet_id: subnet-1c871974 
        region: ca-central-1
        instance_tags:
          Name: CentOS6
        wait: yes
        assign_public_ip: yes


   


    