--- # ansible requires boto3 #sudo pip install boto
- name: Create ec2 instance
  hosts: localhost
  tasks:
    - name: Creates  instances
      ec2:
        key_name: work-mac-key
        instance_type: t2.micro 
        image: ami-0c5204531f799e0c6
        count: 3
        vpc_subnet_id: subnet-9d3120e4
        region: us-west-2