--- # ansible requires boto3 #sudo pip install boto
- name: Create ec2 instance
  hosts: localhost
  tasks:
    - name: Creates ec2 instances
      ec2:
        key_name: local
        instance_type: t2.micro 
        image: ami-074e2d6769f445be5
        count: 3
        vpc_subnet_id: subnet-bfe913d9
        region: us-west-1