--- # ansible requires boto3 #sudo pip install boto
- name: Create ec2 instance
  hosts: localhost
  tasks:
    - name: Creates  instances
      ec2:
        key_name: ansible-private 
        instance_type: t2.micro  
        image: ami-03caa3f860895f82e
        count: 1
        vpc_subnet_id: subnet-dee619b8
        region: us-west-2