---
- name: Terminates instance 
  hosts: localhost
  tasks:
    - name: Terminate instance 
      ec2: 
        instance_ids: i-026a167065e318a34
        state: absent  #stopped #started
        region: us-east-2

