---
- name: Install r1soft server
  hosts: hosts
  become: yes
  become_method: sudo
  tasks:
    # This line for CentOS 6
      # this line is for centos 6    
    - block:
       - name: create r1soft
         copy: 
           src: r1soft.repo
           dest: /etc/yum.repos.d/r1soft.repo

       - name: Install r1soft agent
         package: 
           name: serverbackup-enterprise-agent
           state: present
         notify: r1soft_INSTALLED_ON

       - name: start agent
         service: 
           name: cdp-agent
           state: restarted
      
       - name: get key
         shell: "r1soft-setup --get-key http://r1soft.acirrustech.com"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"