---
- name: Creates Route53 entry
  hosts: localhosts
  tasks:
    - name: Route53 A record
      route53:
      state: "{{state}}"
      zone: "{{zone}}"
      record: "{{record}}"
      type: A 
      ttl: 7200
      value: "{{IP}}"